### ISSUE TITLE
As a developer I would like support for making a Progressive (Evergreen) Web Application

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/create-evergreen-app#7]
## Type of Change
- [x] New Feature Request
- [ ] Documentation
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Progressive Web Applications help bridge the web to the mobile world with an emphasis on performance and offline capabilities.  That said, not every application needs to be one.

## Details
Providing support either through code, documentation, or default behavior,  (or all three) would be the goal of this feature request.

I think for now it's ok have the dependencies installed, with documentation for enabling it.  Or maybe a configuration option in **webpack**?

## Tasks
This issue will likely require a few iterations / discussions
1. [x] Add basic manifest 
1. [ ] Enable Service Worker (installed, but off by default?  enforces HTTPS) - see #8
